### ISSUE TITLE
"Build Model" component.

### ISSUE THREAD

**Issue by bunjii** [CSDG-DDL/PTK#67]
It appears to me that irrelevant to the "filepath" input, the btlx file is saved in the same folder as gh file.

**Comment by bunjii** [comment]
![filepath](https://user-images.githubusercontent.com/16072693/51153610-2676a380-18b4-11e9-9d35-a9a85fc192b1.PNG)

**Comment by johnhaddalmork** [comment]
Fixed!
Added a new btlx component
