### ISSUE TITLE
"Node Plane Rule" input in the "Detailing Group Definition" component

### ISSUE THREAD

**Issue by bunjii** [CSDG-DDL/PTK#68]
Not in a hurry but just wondering what's the functionality of this input. The input is set as Optional, but w/o it, the connecting Assembly component turns red. Could perhaps @johnhaddalmork or @steinady  tell me what's the proper way of using this input (to where the vector input in the Normal Vector Plane componennt should specify) ?

**Comment by bunjii** [comment]
![node plane](https://user-images.githubusercontent.com/16072693/51154576-a2beb600-18b7-11e9-9bc1-54f2b79adf59.PNG)

![node plane 2](https://user-images.githubusercontent.com/16072693/51154577-a2beb600-18b7-11e9-89f9-836bfd67368a.PNG)

**Comment by johnhaddalmork** [comment]
Fixed :-)
