### ISSUE TITLE
"Unified Element Vectors" output in the "Select Detailing Group" component

### ISSUE THREAD

**Issue by bunjii** [CSDG-DDL/PTK#69]
It works as expected with segmented lines, but when I replace the upper & lower chords of the truss in the picture with unsegmented curve, the element vectors deviate from what they should be.

![unified element vectors](https://user-images.githubusercontent.com/16072693/51157194-1fef2880-18c2-11e9-8dcb-e6b0e72c6ac2.PNG)
![unified element vectors with crvs](https://user-images.githubusercontent.com/16072693/51157195-1fef2880-18c2-11e9-8570-cc0bffc7ff98.PNG)

**Comment by TodaYuto** [comment]
I fixed it with this Commit so close it
https://github.com/CSDG-DDL/PTK/commit/76823e9649ebbb129a979b706daed7a23cfb33f6
