### ISSUE TITLE
Intersection Nodes causing trouble

### ISSUE THREAD

**Issue by steinady** [CSDG-DDL/PTK#91]
In the case for Great Court Roof (many elements) i found that interseciton nodes "true" causes many elements to be assigned to one node. 
![image](https://user-images.githubusercontent.com/42492338/54819496-53707980-4c9c-11e9-883c-d894ec3ec73f.png)
![image](https://user-images.githubusercontent.com/42492338/54819551-8ca8e980-4c9c-11e9-9abc-18efbb69b9d3.png)

**Comment by bunjii** [comment]
Hi @steinady , Will you send the file with above symptom for us?

**Comment by johnhaddalmork** [comment]
Hi @bunjii! It turned out to be an tolerance-issue when applying meters. It is now fixed
